### ISSUE TITLE
i++ a little bit slow

### ISSUE THREAD

**Issue by CTimmerman** [glathoud/transfun#10]
According to https://stackoverflow.com/questions/1546981/post-increment-vs-pre-increment-javascript-optimization +=1 is even faster than ++i, which is faster than i++.

**Comment by glathoud** [comment]
Interesting, thanks. Had a quick-and-dirty try in chromium, and over about 6 seconds (60 runs of about 100ms each, 1 sec pause in-between), devtools closed, i got `6307 5829 5801` accumulated runtime.

**Comment by glathoud** [comment]
```js
<script>
    t0=0;t1=0;t2=0;

f();  
function f()
{
    var MAX = 99000000, t=0,i=0;

    t = (new Date()).getTime();
    for ( i=0; i<MAX;i++ ) {}
    t = (new Date()).getTime() - t;
    t0+=t;


    t = (new Date()).getTime();
    for ( i=0; i<MAX;++i ) {}
    t = (new Date()).getTime() - t;
    t1+=t;


    t = (new Date()).getTime();
    for ( i=0; i<MAX;i+=1 ) {}
    t = (new Date()).getTime() - t;
    t2+=t;

    count = f.count = 1 + (f.count | 0);

    if (count < 60)
        setTimeout(f,1000);
    else
        console.log(t0,t1,t2),alert('done');
}
</script>
```

**Comment by CTimmerman** [comment]
You're welcome. I got 8007 6883 8010, 6896 6486 6426, and 6625 6331 6353 in Chrome on 64-bit Windows 10 on an i5. But after reversing the order of those ways, i get 6521 6813 6409, 6392 6390 6721, and 6358 6350 6734. Firefox on my work Dell 5590 didn't have a clear winner either, so it seems like the compiler outputs similar code and the JIT is warming up during the first way. Decrementing gave me 6337 6348 6612, 6157 6145 6576 (var for totals), 6376 6376 6678, 6662 6345 6356 (original order of ways, f.count alone), and 6751 6341 6345:

    var t0 = t1 = t2 = count = 0
    f()
    function f(){
        var MAX = 99000000 - 1, t = 0, i = 0
    
        t = (new Date()).getTime()
        for(i = MAX; i >= 0; i--);
        t = (new Date()).getTime() - t
        t0 += t
    
        t = (new Date()).getTime()
        for(i = MAX; i >= 0; --i);
        t = (new Date()).getTime() - t
        t1 += t
    
        t = (new Date()).getTime()
        for(i = MAX; i >= 0; i -= 1);
        t = (new Date()).getTime() - t
        t2 += t
    
        if(++count < 60) setTimeout(f, 1000)
        else console.log(t0, t1, t2), alert('done')
    }

This also appears to have the JIT warmup issue:

    var MAX = 99e6
    
    function timeit(fun, times=60){
        t = (new Date()).getTime()
        for(var i = 0; i < times; ++i) fun()
        return (new Date()).getTime() - t
    }
    
    function a(){ for(var i = 0; i < MAX; ++i); }
    function b(){ for(var i = 0; i < MAX; i++); }
    function c(){ for(var i = 0; i < MAX; i+=1); }
    function d(){ for(var i = MAX-1; i >= 0; i--); }
    function e(){ for(var i = MAX-1; i >= 0; --i); }
    function f(){ for(var i = MAX-1; i >= 0; i -= 1); }
    
    console.log(timeit(a), timeit(b), timeit(c), timeit(d), timeit(e), timeit(f))

6353 6353 6256 6361 6354 6341
6330 6343 6339 6227 6346 6360
6353 6342 6265 6366 6348 6305 (swapped c and a in log call)

**Comment by glathoud** [comment]
You were right, I tried playing with order and pauses and got no clear winner either. Firefox & Chromium on i5 linux. I guess I'll just put ++i and call it a day :)
